server:
  port: 9876

spring:
  sql:
    init:
      platform: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
  security:
    user:
      name:
      password:

ca:
  secret-url:
  aws:
    s3-bucket:
    region: