spring:
  application:
    name: secret

server:
  port: 6789
  ssl:
    certificate: "classpath:certs/server.pem"
    certificate-private-key: "classpath:certs/server.key"
    trust-certificate: "classpath:certs/cacert.pem"
