spring:
  application:
    name: secret
  ssl:
    bundle:
      jks:
        web-server:
          key:
            alias: "1"
          keystore:
            type: "PKCS12"
            location: "classpath:certs/server.p12"
            password: "123456"
          truststore:
            type: "PKCS12"
            location: "classpath:certs/ca.p12"
            password: "123456"

server:
  port: 6789
  ssl:
    bundle: web-server
    client-auth: NEED
